[project]
name = "authx"
version = "0.1.0"
description = "A comprehensive authentication and authorization microservice"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
    "pydantic>=2.0.0",
    "sqlalchemy>=2.0.0",
    "alembic>=1.12.0",
    "psycopg2-binary>=2.9.7",
    "asyncpg>=0.29.0",
    "passlib>=1.7.4",
    "python-jose>=3.3.0",
    "python-multipart>=0.0.6",
    "bcrypt>=4.0.1",
    "pyjwt>=2.8.0",
    "redis>=5.0.0",
    "email-validator>=2.0.0",
    "python-dotenv>=1.0.0",
    "httpx>=0.24.1",
    "pydantic-settings>=2.0.0",
    "pyotp>=2.9.0",
    "qrcode>=7.4.2",
    "prometheus-client>=0.22.1",
]
