"""
Schemas package initialization for AuthX.
Imports all Pydantic schemas for API requests and responses.
"""

# Base schemas
from .base import (
    BaseSchema,
    TimestampSchema,
    UUIDSchema,
    TenantBaseSchema,
    ResponseBase,
    PaginatedResponse,
    ErrorResponse,
)

# Authentication schemas
from .auth import (
    TokenPayload,
    LoginRequest,
    LoginResponse,
    MFAChallenge,
    MFAVerifyRequest,
    MFAVerifyResponse,
    TokenRefreshRequest,
    TokenRefreshResponse,
    TokenRevokeRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
    PasswordChangeRequest,
    RegisterRequest,
    RegisterResponse,
    EmailVerificationRequest,
    EmailVerificationConfirm,
    SessionInfo,
    SessionListResponse,
    SessionRevokeRequest,
    LogoutRequest,
    LogoutResponse,
    ImpersonationRequest,
    ImpersonationResponse,
    ImpersonationEndRequest,
    SecurityEventCreate,
)

# User schemas
from .user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserPasswordUpdate,
    UserMFASetup,
    UserMFAVerify,
    UserDeviceBase,
    UserDeviceCreate,
    UserDeviceResponse,
    UserResponse,
    UserProfile,
    UserListResponse,
)

# Organization schemas
from .organization import (
    OrganizationBase,
    OrganizationCreate,
    OrganizationUpdate,
    OrganizationResponse,
    OrganizationSettingsBase,
    OrganizationSettingsUpdate,
    OrganizationSettingsResponse,
    OrganizationMemberBase,
    OrganizationMemberCreate,
    OrganizationMemberUpdate,
    OrganizationMemberResponse,
    OrganizationInvitationCreate,
    OrganizationInvitationResponse,
    OrganizationInvitationAccept,
    OrganizationStats,
    OrganizationStatsResponse,
    OrganizationListResponse,
)

# Role schemas
from .role import (
    RoleBase,
    RoleCreate,
    RoleUpdate,
    RoleResponse,
    RolePermissionUpdate,
    RoleAssignment,
    RoleAssignmentResponse,
    PermissionTemplate,
    PermissionTemplateResponse,
    RoleStats,
    RoleStatsResponse,
    RoleListResponse,
)

# Location schemas
from .location import (
    LocationBase,
    LocationCreate,
    LocationUpdate,
    LocationResponse,
    LocationGroupBase,
    LocationGroupCreate,
    LocationGroupUpdate,
    LocationGroupResponse,
    LocationAssignment,
    LocationAssignmentResponse,
    LocationStats,
    LocationStatsResponse,
    LocationListResponse,
)

# Audit schemas
from .audit import (
    AuditLogBase,
    AuditLogCreate,
    AuditLogResponse,
    SecurityEventBase,
    SecurityEventCreate,
    SecurityEventUpdate,
    SecurityEventResponse,
    ComplianceReportBase,
    ComplianceReportCreate,
    ComplianceReportResponse,
    ForensicSnapshotBase,
    ForensicSnapshotCreate,
    ForensicSnapshotResponse,
    AuditLogQuery,
    SecurityEventQuery,
    AuditStats,
    AuditStatsResponse,
    AuditLogListResponse,
    SecurityEventListResponse,
)

# Admin schemas
from .admin import (
    SystemConfigBase,
    SystemConfigCreate,
    SystemConfigUpdate,
    SystemConfigResponse,
    LicenseBase,
    LicenseCreate,
    LicenseUpdate,
    LicenseResponse,
    SystemAlertBase,
    SystemAlertCreate,
    SystemAlertUpdate,
    SystemAlertResponse,
    SystemHealthCheck,
    SystemHealthResponse,
    SystemStats,
    SystemStatsResponse,
    SystemBackupCreate,
    SystemBackupResponse,
    SystemMaintenanceCreate,
    SystemMaintenanceResponse,
    SystemConfigListResponse,
    LicenseListResponse,
    SystemAlertListResponse,
)

__all__ = [
    # Base schemas
    "BaseSchema",
    "TimestampSchema",
    "UUIDSchema",
    "TenantBaseSchema",
    "ResponseBase",
    "PaginatedResponse",
    "ErrorResponse",

    # Authentication
    "TokenPayload",
    "LoginRequest",
    "LoginResponse",
    "MFAChallenge",
    "MFAVerifyRequest",
    "MFAVerifyResponse",
    "TokenRefreshRequest",
    "TokenRefreshResponse",
    "TokenRevokeRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "PasswordChangeRequest",
    "RegisterRequest",
    "RegisterResponse",
    "EmailVerificationRequest",
    "EmailVerificationConfirm",
    "SessionInfo",
    "SessionListResponse",
    "SessionRevokeRequest",
    "LogoutRequest",
    "LogoutResponse",
    "ImpersonationRequest",
    "ImpersonationResponse",
    "ImpersonationEndRequest",
    "SecurityEventCreate",

    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserPasswordUpdate",
    "UserMFASetup",
    "UserMFAVerify",
    "UserDeviceBase",
    "UserDeviceCreate",
    "UserDeviceResponse",
    "UserResponse",
    "UserProfile",
    "UserListResponse",

    # Organization
    "OrganizationBase",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationResponse",
    "OrganizationSettingsBase",
    "OrganizationSettingsUpdate",
    "OrganizationSettingsResponse",
    "OrganizationMemberBase",
    "OrganizationMemberCreate",
    "OrganizationMemberUpdate",
    "OrganizationMemberResponse",
    "OrganizationInvitationCreate",
    "OrganizationInvitationResponse",
    "OrganizationInvitationAccept",
    "OrganizationStats",
    "OrganizationStatsResponse",
    "OrganizationListResponse",

    # Role
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "RoleResponse",
    "RolePermissionUpdate",
    "RoleAssignment",
    "RoleAssignmentResponse",
    "PermissionTemplate",
    "PermissionTemplateResponse",
    "RoleStats",
    "RoleStatsResponse",
    "RoleListResponse",

    # Location
    "LocationBase",
    "LocationCreate",
    "LocationUpdate",
    "LocationResponse",
    "LocationGroupBase",
    "LocationGroupCreate",
    "LocationGroupUpdate",
    "LocationGroupResponse",
    "LocationAssignment",
    "LocationAssignmentResponse",
    "LocationStats",
    "LocationStatsResponse",
    "LocationListResponse",

    # Audit
    "AuditLogBase",
    "AuditLogCreate",
    "AuditLogResponse",
    "SecurityEventBase",
    "SecurityEventCreate",
    "SecurityEventUpdate",
    "SecurityEventResponse",
    "ComplianceReportBase",
    "ComplianceReportCreate",
    "ComplianceReportResponse",
    "ForensicSnapshotBase",
    "ForensicSnapshotCreate",
    "ForensicSnapshotResponse",
    "AuditLogQuery",
    "SecurityEventQuery",
    "AuditStats",
    "AuditStatsResponse",
    "AuditLogListResponse",
    "SecurityEventListResponse",

    # Admin
    "SystemConfigBase",
    "SystemConfigCreate",
    "SystemConfigUpdate",
    "SystemConfigResponse",
    "LicenseBase",
    "LicenseCreate",
    "LicenseUpdate",
    "LicenseResponse",
    "SystemAlertBase",
    "SystemAlertCreate",
    "SystemAlertUpdate",
    "SystemAlertResponse",
    "SystemHealthCheck",
    "SystemHealthResponse",
    "SystemStats",
    "SystemStatsResponse",
    "SystemBackupCreate",
    "SystemBackupResponse",
    "SystemMaintenanceCreate",
    "SystemMaintenanceResponse",
    "SystemConfigListResponse",
    "LicenseListResponse",
    "SystemAlertListResponse",
]
