"""remove_mfa_fields_optimization

Revision ID: 4b602396a06c
Revises: b9dc0eebd99d
Create Date: 2025-09-08 07:38:47.466975+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b602396a06c'
down_revision = 'b9dc0eebd99d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('mfa_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
